name: Publish runbooks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/cloud-platform-tech-docs-publisher:1.9
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd runbooks; bundle exec middleman build --build-dir docs
    - name: Upload Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: docs
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync
          which rsync
      - name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.PUBLISHING_GIT_TOKEN }}
          repository-name: ministryofjustice/cloud-platform-runbooks
          branch: gh-test # The branch the action should deploy to.
          folder: 'site' # The folder the action should deploy.
