name: Publish runbooks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/cloud-platform-tech-docs-publisher:1.9
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd runbooks; bundle exec middleman build --build-dir docs
    - name: Install rsync
      run: |
        apk update && apk install -y rsync
          which rsync
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        token: ${{ secrets.PUBLISHING_GIT_TOKEN }}
        repository-name: ministryofjustice/cloud-platform-runbooks
        branch: gh-test # The branch the action should deploy to.
        folder: 'site' # The folder the action should deploy.
